/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import gestiondelibrerias.*;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author marti
 */
public class ConsultaDeLibros extends javax.swing.JFrame {

    private Libreria sistema;
    public ConsultaDeLibros() {
        initComponents();
    }
    
    public ConsultaDeLibros(Libreria sistema){
        initComponents();
        this.sistema = sistema;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        sepBusqueda = new javax.swing.JSeparator();
        scrBusqueda = new javax.swing.JScrollPane();
        pnlFotos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Libros");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitulo.setText("Titulo:");

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblAutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAutor.setText("Autor:");

        txtAutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGenero.setText("Genero:");

        txtGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        pnlFotos.setPreferredSize(new java.awt.Dimension(450, 300));
        pnlFotos.setLayout(new java.awt.GridLayout());
        scrBusqueda.setViewportView(pnlFotos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrBusqueda)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblAutor)
                        .addGap(17, 17, 17)
                        .addComponent(txtAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblGenero)
                        .addGap(7, 7, 7)
                        .addComponent(txtGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConsultar))
                    .addComponent(sepBusqueda, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        this.consultarLibros();
    }//GEN-LAST:event_btnConsultarActionPerformed

    public void consultarLibros(){
        String genero = txtGenero.getText().toLowerCase();
        String titulo = txtTitulo.getText().toLowerCase();
        String autor = txtAutor.getText().toLowerCase();
        ArrayList<Libro> listaResultado = new ArrayList<Libro>();
        
        for (Libro libro : this.sistema.getListaLibros()) {
            boolean coincideGenero = genero.isEmpty() || libro.getGenero().toLowerCase().contains(genero);
            boolean coincideTitulo = titulo.isEmpty() || libro.getTitulo().toLowerCase().contains(titulo);
            boolean coincideAutor = autor.isEmpty() || libro.getAutor().toLowerCase().contains(autor);
            
            if(genero.isEmpty() && titulo.isEmpty() && autor.isEmpty()){
                JOptionPane.showMessageDialog(
                    this,
                    "No se ha ingresado nada.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
            
            if (coincideGenero && coincideTitulo && coincideAutor) {
                listaResultado.add(libro);
            }
        }
        pnlFotos.removeAll();
        txtGenero.setText("");
        txtTitulo.setText("");
        txtAutor.setText("");
        pnlFotos.revalidate();
        pnlFotos.repaint();
        
        this.generarImagenes(listaResultado);
    }
    
    public void generarImagenes(ArrayList<Libro> librosEncontrados){
        for(Libro libro : librosEncontrados){
            String pathFoto = libro.getFoto();
            ImageIcon icon = new ImageIcon(pathFoto);
            JButton botonLibro = new JButton();
            botonLibro.setIcon(icon);
            botonLibro.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e){
                    JFrame detallesLibro = new JFrame();
                    detallesLibro.setSize(300, 200);
                    detallesLibro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    
                    //Creamos el contenido del JFrame
                    JPanel panel = new JPanel();
                    panel.setLayout(new GridLayout(4, 2));
                    JLabel lblTitulo = new JLabel("Título:");
                    JLabel lblGenero = new JLabel("Género:");
                    JLabel lblAutor = new JLabel("Autor:");
                    JLabel lblEditorial = new JLabel("Editorial:");
                    JLabel lblIsbn = new JLabel("ISBN:");
                    JLabel lblValorTitulo = new JLabel(libro.getTitulo());
                    JLabel lblValorGenero = new JLabel(libro.getGenero());
                    JLabel lblValorAutor = new JLabel(libro.getAutor());
                    JLabel lblValorEditorial = new JLabel(libro.getEditorial());
                    JLabel lblValorIsbn = new JLabel(libro.getIsbn());
                    
                    //Creamos el panel donde irá la foto del libro
                    JPanel panelFoto = new JPanel();
                    panelFoto.setBackground(new java.awt.Color(255, 255, 255));
                    panelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    JLabel lblImagen = new JLabel(icon);
                    panelFoto.add(lblImagen);
                    
                    panel.setPreferredSize(new java.awt.Dimension(582, 467));

                    lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14));
                    lblTitulo.setText("Titulo:");

                    lblIsbn.setFont(new java.awt.Font("Segoe UI", 0, 14));
                    lblIsbn.setText("Isbn:");

                    lblEditorial.setFont(new java.awt.Font("Segoe UI", 0, 14));
                    lblEditorial.setText("Editorial:");

                    lblGenero.setFont(new java.awt.Font("Segoe UI", 0, 14));
                    lblGenero.setText("Genero:");

                    lblAutor.setFont(new java.awt.Font("Segoe UI", 0, 14));
                    lblAutor.setText("Autor:");

                    lblValorTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14));

                    lblValorIsbn.setFont(new java.awt.Font("Segoe UI", 0, 14));

                    lblValorEditorial.setFont(new java.awt.Font("Segoe UI", 0, 14));

                    lblValorGenero.setFont(new java.awt.Font("Segoe UI", 0, 14));

                    lblValorAutor.setFont(new java.awt.Font("Segoe UI", 0, 14));

                    panel.add(lblTitulo);
                    panel.add(lblValorTitulo);
                    panel.add(lblGenero);
                    panel.add(lblValorGenero);
                    panel.add(lblAutor);
                    panel.add(lblValorAutor);
                    panel.add(lblEditorial);
                    panel.add(lblValorEditorial);
                    panel.add(lblIsbn);
                    panel.add(lblValorIsbn);
                    detallesLibro.add(panel);
                    detallesLibro.setVisible(true);
                }
            });
            pnlFotos.add(botonLibro);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaDeLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaDeLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaDeLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaDeLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaDeLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFotos;
    private javax.swing.JScrollPane scrBusqueda;
    private javax.swing.JSeparator sepBusqueda;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
