/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author marti
 */
public class ConsultaDeVentas extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaDeVentas
     */
    public ConsultaDeVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIsbn = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        btnIsbn = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblTituloLibro = new javax.swing.JLabel();
        scrDatos = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        lblEjemplaresVendidos = new javax.swing.JLabel();
        lblTotalGanancia = new javax.swing.JLabel();
        lblTotalRecaudado = new javax.swing.JLabel();
        lblNumEjemplaresVendidos = new javax.swing.JLabel();
        lblNumTotalGanancia = new javax.swing.JLabel();
        lblNumTotalRecaudado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Ventas");

        lblIsbn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblIsbn.setText("Isbn");

        txtIsbn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtIsbn.setText("---");

        btnIsbn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnIsbn.setText("...");

        btnExportar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnExportar.setText("Exportar");

        btnConsultar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblTituloLibro.setBackground(new java.awt.Color(0, 0, 153));
        lblTituloLibro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloLibro.setText("---");

        tblDatos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Cliente", "Factura", "Cantidad", "Precio", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrDatos.setViewportView(tblDatos);

        lblEjemplaresVendidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEjemplaresVendidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEjemplaresVendidos.setText("Ejemplares vendidos:");
        lblEjemplaresVendidos.setMaximumSize(new java.awt.Dimension(130, 20));
        lblEjemplaresVendidos.setMinimumSize(new java.awt.Dimension(130, 20));
        lblEjemplaresVendidos.setPreferredSize(new java.awt.Dimension(130, 20));

        lblTotalGanancia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalGanancia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalGanancia.setText("Total ganancia:");
        lblTotalGanancia.setMaximumSize(new java.awt.Dimension(130, 20));
        lblTotalGanancia.setMinimumSize(new java.awt.Dimension(130, 20));
        lblTotalGanancia.setPreferredSize(new java.awt.Dimension(130, 20));

        lblTotalRecaudado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalRecaudado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalRecaudado.setText("Total Recaudado:");

        lblNumEjemplaresVendidos.setBackground(new java.awt.Color(0, 0, 153));
        lblNumEjemplaresVendidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumEjemplaresVendidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumEjemplaresVendidos.setText("-");

        lblNumTotalGanancia.setBackground(new java.awt.Color(0, 0, 153));
        lblNumTotalGanancia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumTotalGanancia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumTotalGanancia.setText("-");

        lblNumTotalRecaudado.setBackground(new java.awt.Color(0, 0, 153));
        lblNumTotalRecaudado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumTotalRecaudado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumTotalRecaudado.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrDatos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIsbn)
                        .addGap(18, 18, 18)
                        .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIsbn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloLibro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumEjemplaresVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEjemplaresVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumTotalRecaudado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalRecaudado, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNumTotalGanancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalGanancia, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbn)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIsbn)
                    .addComponent(btnExportar)
                    .addComponent(btnConsultar))
                .addGap(18, 18, 18)
                .addComponent(lblTituloLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEjemplaresVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalRecaudado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumEjemplaresVendidos)
                    .addComponent(lblNumTotalRecaudado)
                    .addComponent(lblNumTotalGanancia))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaDeVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnIsbn;
    private javax.swing.JLabel lblEjemplaresVendidos;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblNumEjemplaresVendidos;
    private javax.swing.JLabel lblNumTotalGanancia;
    private javax.swing.JLabel lblNumTotalRecaudado;
    private javax.swing.JLabel lblTituloLibro;
    private javax.swing.JLabel lblTotalGanancia;
    private javax.swing.JLabel lblTotalRecaudado;
    private javax.swing.JScrollPane scrDatos;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtIsbn;
    // End of variables declaration//GEN-END:variables
}
