/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author marti
 */
public class RegistrarGenero extends javax.swing.JFrame {

    /**
     * Creates new form RegistroGenero
     */
    public RegistrarGenero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreGenero = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtNombreGenero = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        sepRegistro = new javax.swing.JSeparator();
        scrDatosIngresados = new javax.swing.JScrollPane();
        txaDatosIngresados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Genero");
        getContentPane().setLayout(null);

        lblNombreGenero.setText("Nombre del genero:");
        getContentPane().add(lblNombreGenero);
        lblNombreGenero.setBounds(30, 20, 130, 16);

        lblDescripcion.setText("Descripcion:");
        getContentPane().add(lblDescripcion);
        lblDescripcion.setBounds(30, 50, 130, 16);

        txtDescripcion.setToolTipText("Descripción");
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(190, 50, 180, 20);

        txtNombreGenero.setToolTipText("Nombre");
        getContentPane().add(txtNombreGenero);
        txtNombreGenero.setBounds(240, 20, 130, 20);

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAñadir);
        btnAñadir.setBounds(279, 80, 90, 20);
        getContentPane().add(sepRegistro);
        sepRegistro.setBounds(10, 110, 380, 10);

        txaDatosIngresados.setEditable(false);
        txaDatosIngresados.setColumns(20);
        txaDatosIngresados.setRows(5);
        scrDatosIngresados.setViewportView(txaDatosIngresados);

        getContentPane().add(scrDatosIngresados);
        scrDatosIngresados.setBounds(20, 130, 360, 470);

        setBounds(0, 0, 416, 681);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarGenero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombreGenero;
    private javax.swing.JScrollPane scrDatosIngresados;
    private javax.swing.JSeparator sepRegistro;
    private javax.swing.JTextArea txaDatosIngresados;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombreGenero;
    // End of variables declaration//GEN-END:variables
}
