/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author marti
 */

import gestiondelibrerias.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class RegistrarGenero extends javax.swing.JFrame {

    /**
     * Creates new form RegistroGenero
     */
    
    private Libreria sistema;
    
    public RegistrarGenero() {
        initComponents();
    }
    
    public RegistrarGenero(Libreria sistema) {
        initComponents();
        
        this.sistema = sistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistro = new javax.swing.JPanel();
        pnlRegistroNombre = new javax.swing.JPanel();
        lblRegistroNombre = new javax.swing.JLabel();
        txtRegistroNombre = new javax.swing.JTextField();
        pnlRegistroDescripcion = new javax.swing.JPanel();
        lblRegistroDescripcion = new javax.swing.JLabel();
        txtRegistroDescripcion = new javax.swing.JTextField();
        pnlRegistroCompletar = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        scrDatos = new javax.swing.JScrollPane();
        lstDatos = new javax.swing.JList<>();
        pnlSeparador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Genero");

        pnlRegistro.setMaximumSize(new java.awt.Dimension(32767, 150));
        pnlRegistro.setMinimumSize(new java.awt.Dimension(10, 150));
        pnlRegistro.setPreferredSize(new java.awt.Dimension(100, 150));
        pnlRegistro.setLayout(new java.awt.BorderLayout());

        pnlRegistroNombre.setMaximumSize(new java.awt.Dimension(32767, 60));
        pnlRegistroNombre.setMinimumSize(new java.awt.Dimension(10, 60));
        pnlRegistroNombre.setPreferredSize(new java.awt.Dimension(100, 60));

        lblRegistroNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegistroNombre.setText("Nombre del genero:");
        lblRegistroNombre.setMaximumSize(new java.awt.Dimension(150, 50));
        lblRegistroNombre.setMinimumSize(new java.awt.Dimension(150, 50));
        lblRegistroNombre.setPreferredSize(new java.awt.Dimension(150, 50));
        pnlRegistroNombre.add(lblRegistroNombre);

        txtRegistroNombre.setMaximumSize(new java.awt.Dimension(100, 30));
        txtRegistroNombre.setMinimumSize(new java.awt.Dimension(100, 30));
        txtRegistroNombre.setPreferredSize(new java.awt.Dimension(100, 30));
        txtRegistroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroNombreActionPerformed(evt);
            }
        });
        pnlRegistroNombre.add(txtRegistroNombre);

        pnlRegistro.add(pnlRegistroNombre, java.awt.BorderLayout.PAGE_START);

        pnlRegistroDescripcion.setMaximumSize(new java.awt.Dimension(32767, 60));
        pnlRegistroDescripcion.setMinimumSize(new java.awt.Dimension(10, 60));
        pnlRegistroDescripcion.setName(""); // NOI18N
        pnlRegistroDescripcion.setPreferredSize(new java.awt.Dimension(100, 60));

        lblRegistroDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegistroDescripcion.setText("Descripción:");
        lblRegistroDescripcion.setMaximumSize(new java.awt.Dimension(100, 50));
        lblRegistroDescripcion.setMinimumSize(new java.awt.Dimension(100, 50));
        lblRegistroDescripcion.setPreferredSize(new java.awt.Dimension(100, 50));
        pnlRegistroDescripcion.add(lblRegistroDescripcion);

        txtRegistroDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRegistroDescripcion.setMaximumSize(new java.awt.Dimension(150, 30));
        txtRegistroDescripcion.setMinimumSize(new java.awt.Dimension(150, 30));
        txtRegistroDescripcion.setPreferredSize(new java.awt.Dimension(150, 30));
        pnlRegistroDescripcion.add(txtRegistroDescripcion);

        pnlRegistro.add(pnlRegistroDescripcion, java.awt.BorderLayout.CENTER);

        pnlRegistroCompletar.setMaximumSize(new java.awt.Dimension(32767, 30));
        pnlRegistroCompletar.setMinimumSize(new java.awt.Dimension(10, 30));
        pnlRegistroCompletar.setPreferredSize(new java.awt.Dimension(100, 30));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        pnlRegistroCompletar.add(btnAgregar);

        pnlRegistro.add(pnlRegistroCompletar, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlRegistro, java.awt.BorderLayout.PAGE_START);

        pnlDatos.setLayout(new java.awt.BorderLayout());

        scrDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scrDatos.setMaximumSize(new java.awt.Dimension(90, 32767));
        scrDatos.setMinimumSize(new java.awt.Dimension(90, 22));
        scrDatos.setPreferredSize(new java.awt.Dimension(90, 100));

        lstDatos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        scrDatos.setViewportView(lstDatos);

        pnlDatos.add(scrDatos, java.awt.BorderLayout.CENTER);
        pnlDatos.add(pnlSeparador, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 336, 457);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegistroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroNombreActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (this.txtRegistroNombre.getText().contains("|") || this.txtRegistroDescripcion.getText().contains("|")) {
            JOptionPane.showMessageDialog(
                this,
                "No se puede utilizar el carácter '|'.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return; // Salimos del método para evitar el registro
        }
        
        if (this.txtRegistroNombre.getText().length() > 0 && this.txtRegistroDescripcion.getText().length() > 0) {
            if (this.sistema.generoRepetido(this.txtRegistroNombre.getText())) {
                // Codigo para cuando el genero esta repetido
                JOptionPane.showMessageDialog(
                    this,
                    "El género ya se encuentra registrado.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            } else {
                // Limpiar las casillas de texto, añadir a la lista de generos en sistema y actualizar la lista
                String nuevoNom = this.txtRegistroNombre.getText().trim();
                String nuevoDesc = this.txtRegistroDescripcion.getText().trim();
                
                Genero nuevoGenero = new Genero(nuevoNom, nuevoDesc);
                this.sistema.agregarGenero(nuevoGenero);
                
                this.guardarGeneroEnArchivo(nuevoGenero);
                
                this.actualizarLista();
                
                this.txtRegistroNombre.setText("");
                this.txtRegistroDescripcion.setText("");
            }
        } else {
            if (!(this.txtRegistroNombre.getText().length() > 0)) {
                // Que hacer cuando no se ingresó un nombre
                JOptionPane.showMessageDialog(
                    this,
                    "No se ha ingresado un nombre.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            } else {
                // Que hacer cuando no se ingresó una descripción
                JOptionPane.showMessageDialog(
                    this,
                    "No se ha ingresado una descripción.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void actualizarLista() {
        DefaultListModel<String> modelo = new DefaultListModel<>();
        
        for (Genero genero : this.sistema.getListaGeneros()) {
            String textoGenero = genero.getNombre() + ": " + genero.getDescripcion();
            modelo.addElement(textoGenero); 
        }
        
        lstDatos.setModel(modelo);
    }
    
    private void guardarGeneroEnArchivo(Genero genero) {
        String rutaArchivo = System.getProperty("user.dir") + File.separator + "datos" + File.separator + "generos.txt";
        File archivo = new File(rutaArchivo);

        try {
            // Crear carpeta "datos" si no existe
            archivo.getParentFile().mkdirs();

            // Abrir el archivo en modo de anexado
            FileWriter writer = new FileWriter(archivo, true);
            writer.write(genero.getNombre() + "|" + genero.getDescripcion() + "\n");
            writer.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                this,
                "Error al guardar el género en el archivo: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarGenero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel lblRegistroDescripcion;
    private javax.swing.JLabel lblRegistroNombre;
    private javax.swing.JList<String> lstDatos;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JPanel pnlRegistroCompletar;
    private javax.swing.JPanel pnlRegistroDescripcion;
    private javax.swing.JPanel pnlRegistroNombre;
    private javax.swing.JPanel pnlSeparador;
    private javax.swing.JScrollPane scrDatos;
    private javax.swing.JTextField txtRegistroDescripcion;
    private javax.swing.JTextField txtRegistroNombre;
    // End of variables declaration//GEN-END:variables
}
